version: "3.8"

services:
  api:
    build:
      context: .
    volumes:
      - .:/project:Z
    working_dir: /project
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/project
      - TF_CPP_MIN_LOG_LEVEL=2
      - MPLCONFIGDIR=/tmp/matplotlib
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
